---
- name: UPYUN-DEV-ROLLBACK | 清理掉目前使用的版本
  file:
    state: absent
    path: "{{ ansistrano_releases_path.stdout }}/{{ ansistrano_current_release_version.stdout }}"
  when: ansistrano_remove_rolled_back
