---
- name: UPYUN-DEV-ROLLBACK | 获取历史版本目录
  command: echo "{{ rollback_from }}/{{ rollback_version_dir }}"
  register: rollback_releases_path

- name: UPYUN-DEV-ROLLBACK | 读取历史发布数量
  shell: echo `ls {{ rollback_releases_path.stdout }} -1t | wc -l`
  register: rollback_versions_count

- name: UPYUN-DEV-ROLLBACK | 检查是否有发布过版本
  fail:
    msg: "没有找到可回滚的历史版本!"
  when: rollback_versions_count.stdout|int <= 1

- name: UPYUN-DEV-ROLLBACK | 获取当前的版本号
  shell: echo `ls -1t {{ rollback_releases_path.stdout }} | head -n 1`
  register: rollback_current_release_version

- name: UPYUN-DEV-ROLLBACK | 获取当前版本的前一次发布版本号
  shell: echo `ls -1t {{ rollback_releases_path.stdout }} | head -n 2 | tail -n 1`
  register: rollback_previous_release_version

- name: UPYUN-DEV-ROLLBACK | 获取前一个版本的目录
  command: echo "{{ rollback_releases_path.stdout }}/{{ rollback_previous_release_version.stdout }}"
  register: rollback_release_path
