---
- name: UPYUN-DEV-ROLLBACK | 获取历史版本目录
  command: echo "{{ updeployment_deploy_to }}/{{ updeployment_version_dir }}"
  register: updeployment_releases_path

- name: UPYUN-DEV-ROLLBACK | 读取历史发布数量
  shell: echo `ls {{ updeployment_releases_path.stdout }} -1t | wc -l`
  register: updeployment_versions_count

- name: UPYUN-DEV-ROLLBACK | 检查是否有发布过版本
  fail:
    msg: "没有找到可回滚的历史版本!"
  when: updeployment_versions_count.stdout|int <= 1

- name: UPYUN-DEV-ROLLBACK | 获取当前的版本号
  shell: echo `ls -1t {{ updeployment_releases_path.stdout }} | head -n 1`
  register: updeployment_current_release_version

- name: UPYUN-DEV-ROLLBACK | 获取当前版本的前一次发布版本号
  shell: echo `ls -1t {{ updeployment_releases_path.stdout }} | head -n 2 | tail -n 1`
  register: updeployment_previous_release_version

- name: UPYUN-DEV-ROLLBACK | 获取前一个版本的目录
  command: echo "{{ updeployment_releases_path.stdout }}/{{ updeployment_previous_release_version.stdout }}"
  register: updeployment_release_path
