---
- name: UPYUN-DEV-ROLLBACK | 重新链接 current 到前一个版本
  file:
    state: link
    path: "{{ rollback_from }}/{{ rollback_current_dir }}"
    src: "./{{ rollback_version_dir }}/{{ rollback_previous_release_version.stdout }}"
