---
- name: UPYUN-DEV-ROLLBACK | 重新链接 current 到前一个版本
  file:
    state: link
    path: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}"
    src: "./{{ ansistrano_version_dir }}/{{ ansistrano_previous_release_version.stdout }}"
